branch-defaults:
  develop:
    environment: GeneOS-dev
  master:
    environment: GeneOS-prd
    group_suffix: null
environment-defaults:
  GeneOS-dev:
    branch: null
    repository: null
  GeneOS-prd:
    branch: master
    repository: null
global:
  application_name: GeneOS-web
  default_ec2_keyname: geneos-common
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
    64bit Amazon Linux/4.5.4
  default_region: eu-west-2
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
