const placeholder = 'https://placeholdit.imgix.net/~text?txtsize=33&txt=318%C3%97180&w=318&h=180';

export const shopGroups = [
  {
    name: 'Ancestry',
    tag: 'ancestry',
  },
  {
    name: 'Health',
    tag: 'health',
  },
  {
    name: 'Wellness',
    tag: 'wellness',
  },
  {
    name: 'Entertainment',
    tag: 'entertainment',
  },
  {
    name: 'All',
    tag: '',
  },
];

export default [
  {
    image: placeholder,
    description: 'Some people with diabetes have a rare, inherited form that can be misdiagnosed. That can impact how effectively the diabetes is treated. Better understand your diabetes diagnosis by learning if you have MODY.',
    name: 'Inherited Diabetes Test',
    price: '$140.02',
    vendor: 'Admera Health',
    tags: ['health'],
  },
  {
    image: placeholder,
    description: 'In the fight against late-onset Alzheimer’s disease, early awareness can make a difference in taking care of your future self',
    name: 'Alzheimer\'s ApoE Test',
    price: '$159.99',
    vendor: 'ADx Healthcare',
    tags: ['health'],
  },
  {
    image: placeholder,
    description: 'Discover the migration paths your ancient ancestors followed, and learn the details of your ancestral makeup.',
    name: 'Geno 2.0',
    price: '$59.99',
    vendor: 'National Geographic',
    tags: ['ancestry'],
  },
  {
    image: placeholder,
    description: 'Mayo Clinic GeneGuide is a genetic testing experience that helps you understand how genetics can affect your health. Get results and information regarding health traits, disease risk, and more.',
    name: 'Mayo Clinic GeneGuide™',
    price: '$159.99',
    vendor: 'Mayo Clinic',
    tags: ['health'],
  },
  {
    image: placeholder,
    description: 'Award-winning diet, nutrition and exercise profile based on your DNA. Learn to live life your way.',
    name: 'Diet Fitness Pro 360',
    price: '$95.99',
    vendor: 'DNAFit',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Learn your body’s sensitivity to many of the foods you eat and the impact your DNA may have on your ability to digest certain foods and nutrients.',
    name: 'Food Sensitivity+',
    price: '$231.99',
    vendor: 'EverlyWell',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Personalized Recommendations + Club Membership',
    name: 'Wine Explorer',
    price: '$44.99',
    vendor: 'Vinome',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Weight loss can be tough. Understanding your DNA can help lighten the load.',
    name: 'Lose It! + embodyDNA',
    price: '$44.99',
    vendor: 'Lose It!',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Take your first step into DNA learning and into a world of possibilities.',
    name: 'DNAPassport',
    price: '$52.49',
    vendor: 'HumanCode',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Put your past on the map. Then follow the story from there.',
    name: 'Regional Ancestry',
    price: '$47.99',
    vendor: 'Insitome',
    tags: ['ancestry'],
  },
  {
    image: placeholder,
    description: 'Find out how knowing your ancestors’ diets influenced yours.',
    name: 'Metabolism',
    price: '$47.99',
    vendor: 'Insitome',
    tags: ['ancestry'],
  },
  {
    image: placeholder,
    description: 'How much of a Neanderthal are you? Find out why it matters.',
    name: 'Neanderthal',
    price: '$47.99',
    vendor: 'Insitome',
    tags: ['ancestry'],
  },
  {
    image: placeholder,
    description: 'Expert guidance for a personalized diet.',
    name: 'Beat Your Genes: Nutrition and Diet Coaching',
    price: '$53.99',
    vendor: 'Arivale',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Think you’ve got what it takes to be an elite athlete? Scope out the competition.',
    name: 'StartLine',
    price: '$40.00',
    vendor: 'DNAFit',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Get to know your metabolism the fast way.',
    name: 'Metabolism+',
    price: '$189.99',
    vendor: 'EverlyWell',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Not sure which path to take through the gym? Let your genes be the guide.',
    name: 'MyTraits Sport for iOS',
    price: '$50.99',
    vendor: 'Intelliseq',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Show your heart some love with expert lifestyle recommendations.',
    name: 'Heart Optimizer: Genetics and Nutrition Coaching',
    price: '$53.99',
    vendor: 'Arivale',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'The best way to plan your meals? Plan to have us help.',
    name: 'Diet Pro',
    price: '$79.99',
    vendor: 'DNAFit',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'The future is full of possibilities. Explore what yours might look like.',
    name: 'BABYGlimpse',
    price: '$49.49',
    vendor: 'HumanCode',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'You and your genes are a team. Learn how to reach your goals together.',
    name: 'GoalGetter',
    price: '$90.00',
    vendor: 'InsideTracker',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Hit the gym with a friend. One who’s half personal trainer, half geneticist.',
    name: 'Fitness Buddy: All-Access Premium',
    price: '$79.99',
    vendor: 'Azumio',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Your dashboard for weight loss.',
    name: 'Diet GENius',
    price: '$53.99',
    vendor: 'Re:Point',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Genetic screening to help you discover how your DNA may affect your family and future children.',
    name: 'CarrierCheck',
    price: '$179.99',
    vendor: 'Sema4',
    tags: ['health'],
  },
  {
    image: placeholder,
    description: 'Consult with a professional coach and learn interesting DNA insights that may help improve your performance.',
    name: 'EnduranceDNA',
    price: '$35.99',
    vendor: 'Carmichael Training Systems',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Want to understand more about your sleeping habits? MySleepInsights reveals how your DNA may contribute to how (and when) you sleep and makes recommendations to help you wake up feeling more rested.',
    name: 'MySleepInsights',
    price: '$42.00',
    vendor: 'MyVytalics',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Find out if you’re predisposed to having familial hypercholesterolemia (FH), an inherited cause of extremely high “bad” cholesterol that can lead to premature cardiovascular disease.',
    name: 'Inherited Cholesterol Test',
    price: '$131.99',
    vendor: 'Admera Health',
    tags: ['health'],
  },
  {
    image: placeholder,
    description: 'Art is all about what’s inside. Where better to start than your DNA?',
    name: 'Personalized Print',
    price: '$109.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Stay warm the DNA way with this one-of-a-kind fashion statement.',
    name: 'Personalized Scarf',
    price: '$189.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'A more personalized reason to take off your shoes at work.',
    name: 'Personalized Socks',
    price: '$89.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Learn how much DHA is in your breast milk and if your genetics might affect the amount of DHA your baby receives.',
    name: 'Breast Milk DHA+',
    price: '$129.99',
    vendor: 'EverlyWell',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Carry your most precious things in a colorful tote that’s as unique as you are.',
    name: 'ACGTote',
    price: '$104.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Working towards wellness? We’ll help you do it well.',
    name: 'Argus: All-Access Premium',
    price: '$79.99',
    vendor: 'Azumio',
    tags: ['wellness'],
  },
  {
    image: placeholder,
    description: 'Curl up on the couch beneath everything that makes you, you',
    name: 'ACGTartan',
    price: '$239.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Proof that jeans and genes go together just fine.',
    name: 'ACGTee',
    price: '$124.99',
    vendor: 'Dot One',
    tags: ['entertainment'],
  },
  {
    image: placeholder,
    description: 'Count calories in a way that really counts.',
    name: 'Calorie Mama: All-Access Premium',
    price: '$79.99',
    vendor: 'Azumio',
    tags: ['wellness'],
  }
];
